#!/bin/bash

#compilar los archivos de implementación .cpp
g++ -W -Wall -c EmpleadoPorComision.cpp
g++ -W -Wall -c EmpleadoBaseMasComision.cpp

#Compilar el main
g++ -W -Wall -o prog_exe main.cpp *.o

#borrar los .o
rm *.o
